// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    LazySlide: typeof import('./src/components/LazySlide.vue')['default']
    SelectCompany: typeof import('./src/components/SelectCompany.vue')['default']
    TwoFactorList: typeof import('./src/components/TwoFactorList.vue')['default']
    TwoFactorValidation: typeof import('./src/components/TwoFactorValidation.vue')['default']
  }
}

export { }
